- build: 2.3.4/centos/7
  image:
    - mesoscloud/chronos:2.3.4-centos-7
    - mesoscloud/chronos:2.3.4-centos
    - mesoscloud/chronos:2.3.4
    - mesoscloud/chronos:latest

- build: 2.3.4/ubuntu/14.04
  image:
    - mesoscloud/chronos:2.3.4-ubuntu-14.04
    - mesoscloud/chronos:2.3.4-ubuntu


- tests:
    - cmd: chronos -h 2> /dev/null | grep 'USAGE.*chronos'

    - cmd: test -f /tmp/secret
      env:
        - SECRET=password
