- build: 2.4.0/centos/7
  image:
    - mesoscloud/chronos:2.4.0-centos-7
    - mesoscloud/chronos:2.4.0-centos
    - mesoscloud/chronos:2.4.0
    - mesoscloud/chronos:latest

- build: 2.4.0/ubuntu/14.04
  image:
    - mesoscloud/chronos:2.4.0-ubuntu-14.04
    - mesoscloud/chronos:2.4.0-ubuntu


- tests:
    - cmd: chronos -h 2> /dev/null | grep 'USAGE.*chronos'

    - cmd: test -f /tmp/secret
      env:
        - SECRET=password
