sudo: required

services:
  - docker

script:
  - |
    set -e
    for path in `find . -name Dockerfile`; do
        echo $path
        docker run --rm -i lukasmartinelli/hadolint < $path
    done
  - |
    set -e
    for path in `find . -name Dockerfile -print0 | xargs -0 -n1 dirname`; do
        echo $path
        cd $path
        docker build .
        cd -
    done
